/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVisitsRouteImport } from './routes/app.visits'
import { Route as AppVisitReportRouteImport } from './routes/app.visit-report'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdvancedReportsRouteImport } from './routes/app.advanced-reports'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitsRoute = AppVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitReportRoute = AppVisitReportRouteImport.update({
  id: '/visit-report',
  path: '/visit-report',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancedReportsRoute = AppAdvancedReportsRouteImport.update({
  id: '/advanced-reports',
  path: '/advanced-reports',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advanced-reports': typeof AppAdvancedReportsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/team': typeof AppTeamRoute
  '/app/users': typeof AppUsersRoute
  '/app/visit-report': typeof AppVisitReportRoute
  '/app/visits': typeof AppVisitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advanced-reports': typeof AppAdvancedReportsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/team': typeof AppTeamRoute
  '/app/users': typeof AppUsersRoute
  '/app/visit-report': typeof AppVisitReportRoute
  '/app/visits': typeof AppVisitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advanced-reports': typeof AppAdvancedReportsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/team': typeof AppTeamRoute
  '/app/users': typeof AppUsersRoute
  '/app/visit-report': typeof AppVisitReportRoute
  '/app/visits': typeof AppVisitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/advanced-reports'
    | '/app/analytics'
    | '/app/attendance'
    | '/app/companies'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/team'
    | '/app/users'
    | '/app/visit-report'
    | '/app/visits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/advanced-reports'
    | '/app/analytics'
    | '/app/attendance'
    | '/app/companies'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/team'
    | '/app/users'
    | '/app/visit-report'
    | '/app/visits'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/advanced-reports'
    | '/app/analytics'
    | '/app/attendance'
    | '/app/companies'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/team'
    | '/app/users'
    | '/app/visit-report'
    | '/app/visits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/visits': {
      id: '/app/visits'
      path: '/visits'
      fullPath: '/app/visits'
      preLoaderRoute: typeof AppVisitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visit-report': {
      id: '/app/visit-report'
      path: '/visit-report'
      fullPath: '/app/visit-report'
      preLoaderRoute: typeof AppVisitReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advanced-reports': {
      id: '/app/advanced-reports'
      path: '/advanced-reports'
      fullPath: '/app/advanced-reports'
      preLoaderRoute: typeof AppAdvancedReportsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvancedReportsRoute: typeof AppAdvancedReportsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVisitReportRoute: typeof AppVisitReportRoute
  AppVisitsRoute: typeof AppVisitsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancedReportsRoute: AppAdvancedReportsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppTeamRoute: AppTeamRoute,
  AppUsersRoute: AppUsersRoute,
  AppVisitReportRoute: AppVisitReportRoute,
  AppVisitsRoute: AppVisitsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
